/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "Azure Space Group",
  "tagline": "Advanced Quantum Navigation & Propulsion",
  "customFields": {
    "deploymentTimestamp": "2025-10-24T16:45:00Z"
  },
  "favicon": "img/favicon.ico",
  "url": "https://szemkoff.github.io",
  "baseUrl": "/azurespacegroup/",
  "organizationName": "szemkoff",
  "projectName": "azurespacegroup",
  "deploymentBranch": "gh-pages",
  "trailingSlash": true,
  "onBrokenLinks": "warn",
  "onBrokenMarkdownLinks": "warn",
  "staticDirectories": [
    "static",
    "public"
  ],
  "plugins": [
    null
  ],
  "i18n": {
    "defaultLocale": "en",
    "locales": [
      "en"
    ],
    "path": "i18n",
    "localeConfigs": {}
  },
  "markdown": {
    "mermaid": true,
    "format": "mdx",
    "mdx1Compat": {
      "comments": true,
      "admonitions": true,
      "headingIds": true
    },
    "anchors": {
      "maintainCase": false
    }
  },
  "themes": [
    "@docusaurus/theme-mermaid"
  ],
  "themeConfig": {
    "mermaid": {
      "theme": {
        "light": "neutral",
        "dark": "forest"
      },
      "options": {
        "fontFamily": "Arial",
        "flowchart": {
          "useMaxWidth": false,
          "htmlLabels": true,
          "padding": 10
        },
        "graph": {
          "useMaxWidth": false,
          "htmlLabels": true,
          "padding": 10
        },
        "themeVariables": {
          "edgeLabelBackground": "#ffffff",
          "tertiaryColor": "#f9f9f9"
        },
        "diagramPadding": 8,
        "gantt": {
          "titleTopMargin": 25,
          "barHeight": 20,
          "barGap": 4,
          "topPadding": 10,
          "sidePadding": 50
        },
        "securityLevel": "loose"
      }
    },
    "image": "img/azure_corp_mark_black.png",
    "navbar": {
      "title": "Azure Space Group",
      "logo": {
        "alt": "Azure Space Group Logo",
        "src": "/azurespacegroup/img/logo.svg"
      },
      "items": [
        {
          "type": "docSidebar",
          "sidebarId": "tutorialSidebar",
          "position": "left",
          "label": "Documentation"
        },
        {
          "to": "/docs/investment/",
          "position": "left",
          "label": "Investment"
        },
        {
          "to": "/blog",
          "label": "Blog",
          "position": "left"
        },
        {
          "to": "/project-status",
          "label": "Project Status",
          "position": "left"
        },
        {
          "href": "https://github.com/szemkoff/azurespacegroup",
          "label": "GitHub",
          "position": "right"
        }
      ],
      "hideOnScroll": false
    },
    "footer": {
      "style": "dark",
      "links": [
        {
          "title": "Documentation",
          "items": [
            {
              "label": "Core Technology",
              "to": "/docs/core-documentation/core-technology"
            },
            {
              "label": "Energy Systems",
              "to": "/docs/core-documentation/energy-systems"
            },
            {
              "label": "Propulsion & Navigation",
              "to": "/docs/core-documentation/propulsion-navigation"
            },
            {
              "label": "Communication Systems",
              "to": "/docs/core-documentation/communication-systems"
            }
          ]
        },
        {
          "title": "More Documentation",
          "items": [
            {
              "label": "Support Systems",
              "to": "/docs/infrastructure-documentation/support-systems"
            },
            {
              "label": "Human-Centric Design",
              "to": "/docs/infrastructure-documentation/human-centric-design"
            },
            {
              "label": "R&D Infrastructure",
              "to": "/docs/research-documentation/research-development"
            },
            {
              "label": "Legal Framework",
              "to": "/docs/research-documentation/legal-regulatory"
            }
          ]
        },
        {
          "title": "Community & Funding",
          "items": [
            {
              "label": "Contributing",
              "to": "/docs/contributing"
            },
            {
              "label": "Tokenization Strategy",
              "to": "/docs/tokenization-strategy"
            },
            {
              "label": "Game-Based Research",
              "to": "/docs/research-documentation/game-based-research-platform"
            },
            {
              "label": "Investment",
              "to": "/docs/investment"
            }
          ]
        },
        {
          "title": "Community",
          "items": [
            {
              "label": "Contributing",
              "to": "/docs/contributing"
            },
            {
              "label": "GitHub",
              "href": "https://github.com/szemkoff/azurespacegroup"
            },
            {
              "label": "Contact Us",
              "href": "mailto:irnbrue@gmail.com"
            }
          ]
        }
      ],
      "copyright": "Copyright © 2025 Azure Space Group. Built with Docusaurus."
    },
    "prism": {
      "theme": {
        "plain": {
          "color": "#393A34",
          "backgroundColor": "#f6f8fa"
        },
        "styles": [
          {
            "types": [
              "comment",
              "prolog",
              "doctype",
              "cdata"
            ],
            "style": {
              "color": "#999988",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "opacity": 0.7
            }
          },
          {
            "types": [
              "string",
              "attr-value"
            ],
            "style": {
              "color": "#e3116c"
            }
          },
          {
            "types": [
              "punctuation",
              "operator"
            ],
            "style": {
              "color": "#393A34"
            }
          },
          {
            "types": [
              "entity",
              "url",
              "symbol",
              "number",
              "boolean",
              "variable",
              "constant",
              "property",
              "regex",
              "inserted"
            ],
            "style": {
              "color": "#36acaa"
            }
          },
          {
            "types": [
              "atrule",
              "keyword",
              "attr-name",
              "selector"
            ],
            "style": {
              "color": "#00a4db"
            }
          },
          {
            "types": [
              "function",
              "deleted",
              "tag"
            ],
            "style": {
              "color": "#d73a49"
            }
          },
          {
            "types": [
              "function-variable"
            ],
            "style": {
              "color": "#6f42c1"
            }
          },
          {
            "types": [
              "tag",
              "selector",
              "keyword"
            ],
            "style": {
              "color": "#00009f"
            }
          }
        ]
      },
      "darkTheme": {
        "plain": {
          "color": "#9CDCFE",
          "backgroundColor": "#1E1E1E"
        },
        "styles": [
          {
            "types": [
              "prolog"
            ],
            "style": {
              "color": "rgb(0, 0, 128)"
            }
          },
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(106, 153, 85)"
            }
          },
          {
            "types": [
              "builtin",
              "changed",
              "keyword",
              "interpolation-punctuation"
            ],
            "style": {
              "color": "rgb(86, 156, 214)"
            }
          },
          {
            "types": [
              "number",
              "inserted"
            ],
            "style": {
              "color": "rgb(181, 206, 168)"
            }
          },
          {
            "types": [
              "constant"
            ],
            "style": {
              "color": "rgb(100, 102, 149)"
            }
          },
          {
            "types": [
              "attr-name",
              "variable"
            ],
            "style": {
              "color": "rgb(156, 220, 254)"
            }
          },
          {
            "types": [
              "deleted",
              "string",
              "attr-value",
              "template-punctuation"
            ],
            "style": {
              "color": "rgb(206, 145, 120)"
            }
          },
          {
            "types": [
              "selector"
            ],
            "style": {
              "color": "rgb(215, 186, 125)"
            }
          },
          {
            "types": [
              "tag"
            ],
            "style": {
              "color": "rgb(78, 201, 176)"
            }
          },
          {
            "types": [
              "tag"
            ],
            "languages": [
              "markup"
            ],
            "style": {
              "color": "rgb(86, 156, 214)"
            }
          },
          {
            "types": [
              "punctuation",
              "operator"
            ],
            "style": {
              "color": "rgb(212, 212, 212)"
            }
          },
          {
            "types": [
              "punctuation"
            ],
            "languages": [
              "markup"
            ],
            "style": {
              "color": "#808080"
            }
          },
          {
            "types": [
              "function"
            ],
            "style": {
              "color": "rgb(220, 220, 170)"
            }
          },
          {
            "types": [
              "class-name"
            ],
            "style": {
              "color": "rgb(78, 201, 176)"
            }
          },
          {
            "types": [
              "char"
            ],
            "style": {
              "color": "rgb(209, 105, 105)"
            }
          }
        ]
      },
      "additionalLanguages": [],
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "colorMode": {
      "defaultMode": "light",
      "disableSwitch": false,
      "respectPrefersColorScheme": false
    },
    "docs": {
      "versionPersistence": "localStorage",
      "sidebar": {
        "hideable": false,
        "autoCollapseCategories": false
      }
    },
    "blog": {
      "sidebar": {
        "groupByYear": true
      }
    },
    "metadata": [],
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    }
  },
  "presets": [
    [
      "classic",
      {
        "docs": {
          "sidebarPath": "/home/runner/work/azurespacegroup/azurespacegroup/sidebars.js",
          "editUrl": "https://github.com/szemkoff/azurespacegroup/tree/main/"
        },
        "blog": {
          "onInlineAuthors": "ignore",
          "onUntruncatedBlogPosts": "ignore",
          "showReadingTime": true,
          "editUrl": "https://github.com/szemkoff/azurespacegroup/tree/main/"
        },
        "theme": {
          "customCss": "/home/runner/work/azurespacegroup/azurespacegroup/src/css/custom.css"
        }
      }
    ]
  ],
  "baseUrlIssueBanner": true,
  "future": {
    "experimental_faster": {
      "swcJsLoader": false,
      "swcJsMinimizer": false,
      "swcHtmlMinimizer": false,
      "lightningCssMinimizer": false,
      "mdxCrossCompilerCache": false,
      "rspackBundler": false
    },
    "experimental_storage": {
      "type": "localStorage",
      "namespace": false
    },
    "experimental_router": "browser"
  },
  "onBrokenAnchors": "warn",
  "onDuplicateRoutes": "warn",
  "scripts": [],
  "headTags": [],
  "stylesheets": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false
};
