name: Clear GitHub Actions Cache

on:
  workflow_dispatch:
    inputs:
      key:
        description: 'Cache key to delete (leave empty to delete all caches)'
        required: false
        type: string
      confirm:
        description: 'Type "yes" to confirm clearing the cache'
        required: true
        type: string
        default: 'no'

jobs:
  clear-cache:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    if: github.event.inputs.confirm == 'yes'
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: List all caches
        run: |
          echo "Listing all GitHub Actions caches..."
          gh cache list
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Clear cache by key
        if: github.event.inputs.key != ''
        run: |
          echo "Clearing cache with key: ${{ github.event.inputs.key }}"
          gh cache delete --key "${{ github.event.inputs.key }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Clear all caches
        if: github.event.inputs.key == ''
        run: |
          echo "Clearing all caches..."
          gh cache list --limit 100 --json id --jq '.[].id' | xargs -I {} gh cache delete {}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }} 