name: Clear GitHub Pages Cache

on:
  workflow_dispatch:

jobs:
  clear-cache:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Push empty commit to gh-pages
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git fetch origin gh-pages
          git checkout gh-pages
          git commit --allow-empty -m "Force rebuild to clear cache"
          git push origin gh-pages 